### ISSUE TITLE
Hardware profiles searched for in installed package

### ISSUE THREAD

**Issue by dspruell** [jbremer/vmcloak-deps#9]
Ubuntu 14.04 LTS 64-bit
Python 2.7.6
VMCloak 0.2

Both using system Python (standard) installation, as well as installation in a virtualenv, specifying for vmcloak to apply a hardware profile results in an exception as it attempts to load the profile file from the deployed package (e.g. *.../data/hwconf/{profile}.json*) instead of *$HOME/.vmcloak/hwconf/*.

```
# configs/win7-x64.conf
...
hwconfig_profile = laptop
```

```
$ vmcloak -s configs/win7-x64.conf --no-register-cuckoo --dependencies silverlight5 cuckoo1
Warning: creating filesystem that does not conform to ISO-9660.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 290, in <module>
    main()
  File "/usr/local/bin/vmcloak", line 215, in main
    initialize_vm(m, s, h, clone=False)
  File "/usr/local/lib/python2.7/dist-packages/vmcloak/vm.py", line 213, in initialize_vm
    m.init_vm(profile=s.hwconfig_profile)
  File "/usr/local/lib/python2.7/dist-packages/vmcloak/abstract.py", line 147, in init_vm
    hwconf = load_hwconf(profile=profile)
  File "/usr/local/lib/python2.7/dist-packages/vmcloak/conf.py", line 112, in load_hwconf
    conf = json.load(open(os.path.join(dirpath, fname), 'rb'))
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/vmcloak/data/hwconf/laptop.json'
```

**Comment by jbremer** [comment]
Ah, initially the idea was that somebody could make their own, but also that VMCloak would ship a couple. However, as I haven't instructed anyone about it (except for maybe 1-2) people nobody's really using it yet. Should probably write a blogpost or so about it ;)
To fix this I'll have to check both directories for a candidate, with $HOME taking more precedence.

**Comment by dspruell** [comment]
With a hardware profile set in the configuration, and using VirtualBox for virtualization, should obvious elements such as system type, virtual CD-ROM and virtual HDDs no longer display VBox/innotek GmbH identifiers?

**Comment by jbremer** [comment]
That's the idea, yes.
